---
- name: Install Nginx
  apt:
    name: nginx
    update_cache: true
    state: latest

- name: Copy Nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart Nginx

- name: Create index file
  file:
    src: index.html
    dest: /var/www/html/index.html

- name: Ensure Nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: true